openapi: 3.0.1
info:
  title: Documentación de app web de adopción de mascotas
  description: API para una aplicación de adopción de mascotas
  version: 1.0.0

paths:
  # Mascotas
  /api/pets:
    get:
      summary: Obtiene todas las mascotas disponibles
      tags:
        - Pets
      responses:
        "200":
          description: Lista de mascotas obtenidas con éxito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        "500":
          description: Error interno del servidor
    post:
      summary: Crea una nueva mascota
      tags:
        - Pets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/createPet'
      responses:
        "201":
          description: Mascota creada con éxito
        "500":
          description: Error al crear la mascota

  # Registro de usuario
  /api/sessions/register:
    post:
      summary: Registra un nuevo usuario
      tags:
        - Sessions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/createUser'
      responses:
        "201":
          description: Usuario registrado con éxito
        "400":
          description: Error en los datos proporcionados

  # Adopción
  /api/adoptions/{uid}/{pid}:
    post:
      summary: Realiza el proceso de adopción de una mascota
      tags:
        - Adoptions
      parameters:
        - name: uid
          in: path
          required: true
          description: ID del usuario que realiza la adopción
          schema:
            type: string
        - name: pid
          in: path
          required: true
          description: ID de la mascota que se adopta
          schema:
            type: string
      responses:
        "200":
          description: Adopción realizada con éxito
        "400":
          description: Error en los parámetros proporcionados

components:
  schemas:
    Pet:
      type: object
      properties:
        _id:
          type: string
          description: ID de la mascota
        name:
          type: string
          description: Nombre de la mascota
        specie:
          type: string
          description: Especie de la mascota (Ej. Perro, Gato)
        birthDate:
          type: string
          format: date
          description: Fecha de nacimiento de la mascota
        adopted:
          type: boolean
          description: Estado de adopción de la mascota
        owner:
          type: string
          description: ID del propietario (usuario) de la mascota
        image:
          type: string
          description: URL de la imagen de la mascota
      example:
        _id: 60f85a3f8b8c4e301f89b7b3
        name: "Firulais"
        specie: "Perro"
        birthDate: "2020-05-15"
        adopted: false
        owner: "60f85a3f8b8c4e301f89b7b3"
        image: "https://example.com/imagen.jpg"

    User:
      type: object
      properties:
        _id:
          type: string
          description: ID del usuario
        first_name:
          type: string
          description: Nombre del usuario
        last_name:
          type: string
          description: Apellido del usuario
        email:
          type: string
          description: Correo electrónico del usuario
        password:
          type: string
          description: Contraseña del usuario
        role:
          type: string
          description: Rol del usuario (por ejemplo, "user" o "admin")
        pets:
          type: array
          items:
            type: string
            description: IDs de las mascotas del usuario
          description: Lista de mascotas asociadas al usuario
      example:
        _id: 60f85a3f8b8c4e301f89b7b3
        first_name: "Federico"
        last_name: "Osandón"
        email: "federico@gmail.com"
        password: "$2a$10$wDb5zx.e.LhZcy5Gjd9yXo.fPczBOG1bY7l1p48DtL7mL2gr.xOG"
        role: "user"
        pets: ["60f85a3f8b8c4e301f89b7b3", "60f85a3f8b8c4e301f89b7b4"]

  requestBodies:
    createUser:
      type: object
      properties:
        first_name:
          type: string
          description: Nombre del usuario
        last_name:
          type: string
          description: Apellido del usuario
        email:
          type: string
          description: Correo electrónico del usuario
        password:
          type: string
          description: Contraseña del usuario
      example:
        first_name: "Federico"
        last_name: "Osandón"
        email: "fedeuserapi@gmail.com"
        password: "123456"

    createPet:
      type: object
      properties:
        name:
          type: string
          description: Nombre de la mascota
        specie:
          type: string
          description: Especie de la mascota
        birthDate:
          type: string
          format: date
          description: Fecha de nacimiento de la mascota
        image:
          type: string
          description: URL de la imagen de la mascota
      example:
        name: "Firulais"
        specie: "Perro"
        birthDate: "2020-05-15"
        image: "https://example.com/imagen.jpg"
